export default [
    {
        id: 1,
        title: 'Escolher qual framework utilizar',
        user: 'Igor Cezatte',
        avatar: "https://avatars.githubusercontent.com/u/19882853?v=4",
        position: 1,
        isDone: false,
        todo: 'what',
    },
    {
        id: 2,
        title: 'Configurar estrutura do projeto',
        user: 'Igor Cezatte',
        avatar: "https://avatars.githubusercontent.com/u/19882853?v=4",
        position: 2,
        isDone: false,
        todo: 'what',
    },
    {
        id: 3,
        title: 'Finalizar página inicial',
        user: 'Igor Cezatte',
        avatar: "https://avatars.githubusercontent.com/u/19882853?v=4",
        position: 3,
        isDone: false,
        todo: 'what',
    },
    {
        id: 4,
        title: 'Finalizar layout de header e corpo',
        user: 'Igor Cezatte',
        avatar: "https://avatars.githubusercontent.com/u/19882853?v=4",
        position: 4,
        isDone: false,
        todo: 'what',
    },
    {
        id: 5,
        title: 'Finalizar listas de toDo e completed',
        user: 'Igor Cezatte',
        avatar: "https://avatars.githubusercontent.com/u/19882853?v=4",
        position: 5,
        isDone: false,
        todo: 'what',
    },
];